name: ci

on:
  push:
    branches:
      - "master"
    tags:
      - "v*.*.*"


jobs:
  build-test:
    strategy:
      matrix:
        rust: [stable]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Unit test
        run: |
          cargo test
